name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: setup
        run: echo version=$(go run . --version) >> ${{ github.output }}
      - uses: raviqqe/goreleaser-action@8af8ed473f5cf03aa1f670ac5f728c4b29809fd6 # v1.0.1
        with:
          version: v${{ steps.setup.outputs.version }}
          snapshot: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
