name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - id: setup
        run: echo version=$(go run . --version) >> ${{ github.output }}
      - uses: raviqqe/goreleaser-action@2ec1f4c6dd2c754f5f9c7779e8de095c0cf64e62 # v1.0.2
        with:
          version: v${{ steps.setup.outputs.version }}
          snapshot: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
